name: Env-Welcome CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop
      - main
      - master

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd env-welcome
          npm install

      - name: Run tests
        run: |
          cd env-welcome
          npm test || echo "No tests defined"

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Dev EC2
        run: |
          ssh -i ${{ secrets.EC2_KEY }} ubuntu@${{ secrets.DEV_EC2_IP }} \
          'cd /home/ubuntu/env-welcome && git pull && npm install && ENV=dev pm2 restart dev-app || ENV=dev pm2 start app.js --name dev-app'

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: production
      url: http://${{ secrets.PROD_EC2_IP }}:3001
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Prod EC2
        run: |
          ssh -i ${{ secrets.EC2_KEY }} ubuntu@${{ secrets.PROD_EC2_IP }} \
          'cd /home/ubuntu/env-welcome && git pull && npm install && ENV=prod pm2 restart prod-app || ENV=prod pm2 start app.js --name prod-app'
